language: go

sudo: required

services:
  - docker

go:
 - 1.7
 - 1.8
 - tip

install:
 - go get github.com/golang/protobuf/{proto,protoc-gen-go}

script:
 - go test $(go list ./... | grep -v /vendor/)
