language: go

sudo: required

services:
  - docker

go:
 - 1.7
 - 1.8
 - tip

before_install:
  - go get github.com/kardianos/govendor

install:
 - go get github.com/golang/protobuf/{proto,protoc-gen-go}
 - govendor fetch +external

script:
 - go test $(go list ./... | grep -v /vendor/)
